### ISSUE TITLE
Where is the paper ？

### ISSUE THREAD

**Issue by wangchangquan** [wenqing-2021/On_Ramp_Merge_Safe_RL#1]
Where is the paper for your code? I did not find the paper you mentioned when I searched online.

**Comment by wenqing-2021** [comment]
The manuscript is still under review, and I'll post the link after it's published. Thanks for your attention :)

**Comment by wenqing-2021** [comment]
hi, I just uploaded this manuscript into the arXiv: https://arxiv.org/abs/2503.02624.
